// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * Auto-generated INavsCallbacks Interface
 * 
 * Defines all the typed callback functions for NAVS function execution.
 * Implement this interface in your contract to receive type-safe callbacks.
 * 
 * Usage:
 * 1. Extend NavsReceiver abstract contract (which implements this interface)
 * 2. Override the callback methods you need (onGetBtcPrice, etc.)
 * 
 * Generated by navs-gen on 2025-06-02T22:13:29.034Z
 */
interface INavsCallbacks {
    /**
     * Callback for isAddressSanctioned function completion
     * @param taskId The unique identifier for the completed task
     * @param address_param Original parameter of type address
     * @param result The result returned by isAddressSanctioned
     * @param error Error message if the function failed, empty string if successful
     */
    function onIsAddressSanctioned(bytes32 taskId, address address_param, bool result, string memory error) external;
}
