[profile.default]
src = "app/contracts/src"
out = "out"
libs = ["lib"]
remappings = [
    "navs/=../../contracts-l2/",
    "forge-std/=lib/forge-std/src/",
    "@aml/=contracts/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
