[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "navs/=lib/navs/contracts-l2/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
